# Generated by Django 4.2.27 on 2026-01-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='prospect_form_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
