# Generated by Django 4.2.27 on 2026-01-30 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0002_responses_prospect_form_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='prospect.question')),
            ],
        ),
    ]
