# Generated by Django 4.2.27 on 2026-01-30 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0003_selectoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectoption',
            old_name='option_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='selectoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectoption',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectoption',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
