# Generated by Django 4.2.27 on 2026-01-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0005_prospect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnairelog',
            name='details',
        ),
        migrations.RemoveField(
            model_name='questionnairelog',
            name='questionnaire',
        ),
        migrations.AddField(
            model_name='questionnairelog',
            name='form_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
