# Generated by Django 4.2.27 on 2026-02-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0006_remove_questionnairelog_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectoption',
            name='question',
        ),
        migrations.AddField(
            model_name='selectoption',
            name='questions',
            field=models.ManyToManyField(related_name='options', to='prospect.question'),
        ),
    ]
