# Generated by Django 4.2.27 on 2026-02-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0007_remove_selectoption_question_selectoption_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prospect',
        ),
    ]
